# datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: hu020808

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5t5yJCaaoyizY2AJDRHm
  accessKeySecret: weXPuvfzR4BnV1YGr9ayqnSqyoRF4K
  bucketName: result-entry-demo


# mybatis
#mapper映射文件路径
# config-location: #核心配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.springbootmybatis.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

swagger:
  enabled: true

server:
  port: 8888
